### ISSUE TITLE
require sm at /home/dan/zs/cuda118/bmf/bmf/hml/src/core/stream.cpp:130, Stream on device type 1 is not supported

### ISSUE THREAD

**Issue by zhangsong1234** [BabitMF/bmf#102]
## Python Stack ignored
Stack trace (most recent call last):
#5    Object "/usr/bin/python3.8", at 0x5d6065, in _PyObject_MakeTpCall
#4    Object "/usr/bin/python3.8", at 0x5d5498, in PyCFunction_Call
#3    Object "/home/dan/zs/cuda118/bmf/output/bmf/lib/_hmp.cpython-38-x86_64-linux-gnu.so", at 0x7fe59311d0f4, in PyInit__hmp
#2    Object "/home/dan/zs/cuda118/bmf/output/bmf/lib/_hmp.cpython-38-x86_64-linux-gnu.so", at 0x7fe593113266, in 
#1    Object "/home/dan/zs/cuda118/bmf/output/bmf/lib/libhmp.so.1", at 0x7fe592ef2948, in hmp::current_stream(hmp::Device::Type)
#0    Object "/home/dan/zs/cuda118/bmf/output/bmf/lib/libhmp.so.1", at 0x7fe592eec1b9, in hmp::logging::dump_stack_trace(int)
Traceback (most recent call last):
  File "detect_trt_sample.py", line 41, in <module>
    main()
  File "detect_trt_sample.py", line 13, in main
    trt_face_detect = bmf.create_module(
  File "/home/dan/zs/cuda118/bmf/output/bmf/builder/bmf.py", line 28, in create_module
    return engine.Module(module_info, json.dumps(option), "", "", "")
  File "/home/dan/zs/cuda118/bmf/output/demo/face_detect/trt_face_detect.py", line 90, in __init__
    self.stream_ = mp.current_stream(mp.kCUDA)
RuntimeError: require sm at /home/dan/zs/cuda118/bmf/bmf/hml/src/core/stream.cpp:130, Stream on device type 1 is not supported

**Comment by JackLau1222** [comment]
Could you provide the demo code?
